sudo: required

services:
  - docker

jobs:
  include:
    - stage: melodic
      script:
        - docker build --build-arg ROS=melodic -f Dockerfile -t melodic_image .
        - docker run --rm -it -v $PWD:/root/catkin_ws/src/repo melodic_image /bin/bash -c "cd catkin_ws && catkin build && . devel/setup.bash && catkin run_tests && catkin_test_results"
    - stage: noetic
      script:
        - docker build -f Dockerfile.noetic -t noetic_image .
        - docker run --rm -it -v $PWD:/root/catkin_ws/src/repo noetic_image /bin/bash -c "cd catkin_ws && catkin build && . devel/setup.bash && catkin run_tests && catkin_test_results"
